# User Test
#------------------------------------
SHELL = /bin/bash
APP              = factory
APP_SRCS        += factory.c
APP_INC	        +=
APP_CFLAGS      +=


#PMSIS_OS=freertos
platform = gvsoc



include $(RULES_DIR)/pmsis_rules.mk
